name: Docker Image Build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'JMusicBot version'     
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set environment variables
      run: |
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        echo "VCS_REF=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          BUILD_DATE=${{ env.BUILD_DATE }}
          VCS_REF=${{ env.VCS_REF }}
          VERSION=${{ env.VERSION }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jmusicbot-fork:${{ env.VERSION }}
          ${{ secrets.DOCKER_USERNAME }}/jmusicbot-fork:latest
